### ISSUE TITLE
list Index out of range

### ISSUE THREAD

**Issue by DonDavici** [DonDavici/DreamPlex#244]
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Components/ActionMap.py", line 46, in action
    res = self.actions[action]()
  File "/usr/lib/enigma2/python/Plugins/Extensions/DreamPlex/DP_Player.py", line 457, in playNextEntry
    self.playMedia()
  File "/usr/lib/enigma2/python/Plugins/Extensions/DreamPlex/DP_Player.py", line 215, in playMedia
    selection = self.listViewList[self.currentIndex]
IndexError: list index out of range
(PyObject_CallObject(<bound method ActionMap.action of <Components.ActionMap.ActionMap instance at 0x2a59a58>>,('DPS_Player', 'playNext')) failed)

**Comment by klpe1957** [comment]
Have this problem with Version 2.1.3 today. Any news about this?
