### ISSUE TITLE
gs with pin

### ISSUE THREAD

**Issue by DonDavici** [DonDavici/DreamPlex#275]
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Components/ActionMap.py", line 46, in action
    res = self.actions[action]()
  File "/usr/lib/enigma2/python/Plugins/Extensions/DreamPlex/DP_ServerMenu.py", line 195, in onKeyGreen
    self.displayOptionsMenu()
  File "/usr/lib/enigma2/python/Plugins/Extensions/DreamPlex/DP_ServerMenu.py", line 211, in displayOptionsMenu
    self.homeUsersObject = DPS_Users(self.session, self.g_serverConfig.id.value, self.plexInstance)
  File "/usr/lib/enigma2/python/Plugins/Extensions/DreamPlex/DP_Users.py", line 87, in __init__
    tree = getXmlContent(self.location)
  File "/usr/lib/enigma2/python/Plugins/Extensions/DreamPlex/__common__.py", line 803, in getXmlContent
    xml = open(location).read()
IOError: [Errno 2] No such file or directory: '/media/usb/dreamplex/config/homeUsers'
(PyObject_CallObject(<bound method HelpableActionMap.action of <Components.ActionMap.HelpableActionMap instance at 0x2474e18>>,('DP_MainMenuActions', 'green')) failed)

**Comment by DonDavici** [comment]
ohne log file nicht nachvollziehbar :-(
