### ISSUE TITLE
DreamPlex Crash E2

### ISSUE THREAD

**Issue by tryido** [DonDavici/DreamPlex#285]
Hello
I installed on my Dreamplex Cloud-Ibox 3 with OpenPLi4, but when I try to start my server from the decoder program crashes resulting in this error:

ERROR: accelAlloc failed
action ->  SetupActions cancel
action ->  DP_MainMenuActions right
action ->  DP_MainMenuActions ok
<enigma.eVideoWidget; proxy of <Swig Object of type 'eVideoWidget *' at 0x1bcc848> >
action ->  DP_MainMenuActions right
action ->  DP_MainMenuActions ok
authHeaderPartOne {}
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Components/ActionMap.py", line 46, in action
  File "/usr/lib/enigma2/python/Plugins/Extensions/DreamPlex/DP_ServerMenu.py", line 352, in okbuttonClick
    self.getServerData("tvshow")
  File "/usr/lib/enigma2/python/Plugins/Extensions/DreamPlex/DP_ServerMenu.py", line 550, in getServerData
    serverData = self.plexInstance.getAllSections(myFilter=filterBy, serverFilterActive=serverFilterActive)
  File "/usr/lib/enigma2/python/Plugins/Extensions/DreamPlex/DP_PlexLibrary.py", line 432, in getAllSections
    self.saveSectionCache()
  File "/usr/lib/enigma2/python/Plugins/Extensions/DreamPlex/DP_PlexLibrary.py", line 1091, in saveSectionCache
    fd = open(self.sectionCache, "wb")
IOError: [Errno 2] No such file or directory: '/hdd/dreamplex/cache/sections.cache'
(PyObject_CallObject(<bound method HelpableActionMap.action of <Components.ActionMap.HelpableActionMap instance at 0x1cab0a8>>,('DP_MainMenuActions', 'ok')) failed)

**Comment by tryido** [comment]
Problem solved, was the wrong path folders Dreamplex;)

**Comment by DonDavici** [comment]
good to know. thx :-)
